spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    cache: false
  application:
    name: textchecker
#
#  datasource:
#    url: jdbc:h2:mem:testdb
#    driver-class-name: org.h2.Driver
#    username: sa
#    password:

  datasource:
    url: jdbc:mysql://52.91.0.205:3306/textchecker_db?useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true  # ✅ 關鍵：等 Entity 建好再執行 data.sql

  sql:
    init:
      mode: always  # ✅ 保證 data.sql 會執行
server:
  port: 8080
  address: 0.0.0.0
